### ISSUE TITLE
keyboard issue

### ISSUE THREAD

**Issue by tvelter** [agent-007/m9.r00t#1]
After installing m9.r00t, I can't use my keyboard, it disappear without any reason ...

**Comment by agent-007** [comment]
- what keyboard are you using ? 
- firmware version ?

**Comment by tvelter** [comment]
M9 2.3.5 Firmware - version: V2.0.4-10373
baseband 223

I use default keyboard (and tried with ICS keyboard from market, cant even set it to run)

**Comment by agent-007** [comment]
- run "adb logcat";
- try to run keyboard;
- show me the logs.

**Comment by tvelter** [comment]
http://pastebin.com/UCKivcAV

**Comment by tvelter** [comment]
for information, even after removing m9.r00t, the keyboard still has problem.

countless re-installations of the firmware and I faced the exact same issue every single time !

**Comment by agent-007** [comment]
looks like a bug in default keyboard. 

workaround:
- install any keyboard you want;
- install go keyboard from market;
- in Go Keyboard settings select preferred keyboard.

**Comment by tvelter** [comment]
I installed go keyboard.

I switched to go keyboard and it seems to work, but then my phone automatically switch to default keyboard which still have issue. Then i can't switch back to go keyboard

**Comment by tvelter** [comment]
Seems that the issue is related to firmware 2.0.4-10373
Firmware 2.0.3-9345 have no problem.

I'm missing some improvements from the latest firmware, but root seems more essential to me.
thanks
